---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hetzner-csi-driver
  namespace: argocd
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  sources:
    - repoURL: git@github.com:flynnt-io/flynnt-minio-sample.git
      path: applications/hetzner-csi-driver
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator
  sources:
    - repoURL: https://operator.min.io/
      chart: operator
      targetRevision: 5.0.9
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-tenant
  sources:
    - repoURL: git@github.com:flynnt-io/flynnt-minio-sample.git
      path: applications/minio
      targetRevision: HEAD
      ref: values
    - repoURL: https://operator.min.io/
      chart: tenant
      targetRevision: 5.0.9
      helm:
        valueFiles:
          - $values/applications/minio/values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true