apiVersion: v1
clusters:
- cluster:
    server: https://fragrant-wind-4880.cloud.flynnt.io
  name: default
contexts:
- context:
    cluster: default
    user: oidc
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://auth.app.flynnt.io/realms/flynnt
      - --oidc-client-id=flynnt_browser
      - --oidc-use-pkce